name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1

    - name: Initialize MongoDB
      run: sh scripts/initdb-docker.sh

    - name: Build
      run: cargo build

    - name: Test
      run: make test

